export const metricValue = {
    "FCP":{
        minValue:1.8,
        maxValue:3,
        timeUnit:1,
    },
    "LCP":{
        minValue:2.5,
        maxValue:4,
        timeUnit:1,
    },
    "CLS":{
        minValue:0.1,
        maxValue:0.25,
        timeUnit:3,
    },
    "TBT":{
        minValue:200,
        maxValue:600,
        timeUnit:2,
    },
    "TTFB":{
        minValue:800,
        maxValue:1800,
        timeUnit:2,
    },
    "FID":{
     minValue:100,
     maxValue:300,
     timeUnit:2,
    },
    "FMP":{
        minValue:2,
        maxValue:4,
        timeUnit:1,
    },
    "MPFID":{
        minValue:130,
        maxValue:250,
        timeUnit:2
    }
}